linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  golint:
    min-confidence: 0.3
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
    ignore-words: []

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - scopelint
    - structcheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl

service:
  golangci-lint-version: 1.23.x
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repository"
