name: Go

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Set up Go ^1.13
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13'
        id: go

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          make test
